#!/bin/bash
# read- menu :a menu driven system information program
DELAY=3
while true; do
clear
cat <<- _EOF_
Please Select:
	
	1. Display System Information
	2. Display Disk Space
	3. Display Home Space Utilization
	0. Quit

_EOF_

read -p "Enter selection[0-3]> "

case $REPLY in

#if [[ $REPLY=~^[0-3]$ ]]; then 
#	if [[ $REPLY == 0 ]]; then
	0)	echo "Program terminated."
		exit
 		;;

#	fi
#	if [[ $REPLY == 1 ]];then 
	1)	echo "Hostname: $HOSTNAME"
		uptime
		sleep $DELAY
#		continue
		;;
#	fi
#	if [[ $REPLY == 2 ]]; then  
	2)
		df -h
		sleep $DELAY
#		continue
		;;
#	fi
#	if [[ $REPLY == 3 ]]; then 
	3)
		if [[ $(id -u) -eq 0 ]]; then 
			echo "Home Space Utilization (All users)"
			du -sh /home/*
		else 
			echo "Home Space Utilization($USER)"
			du -sh $HOME
		fi
		sleep $DELAY
		;;		
#		continue
#	fi

#else
 *)
	echo "Invalid entry." >&2
	sleep $DELAY
	;;
#fi

#echo "Program terminated"
esac
done
