#!/bin/bash
# loan_calc : script to calculate monthly loan payments

PROGNAME=$(basename $0)

usage(){

	cat<<- _EOF_
	Usage: $PROGNAME PRINCIPAL INTEREST MONTHS
	Where: 
	PRINCIPAL is the amount of the loan.
	INTEREST is the APR as a number (7% =0.07) 
	MONTHS is the length of the loan's term
	_EOF_

}

while true; do
	cat<<- EOF
	0）quit
	1) 输入本金利率时间。
	2) help
	EOF
	
	read -p "so your choice is> "
	case $REPLY in
	0) exit
		;;
	1) read -p "please key principal > " principal
	   read -p "please key interset > " interest
	   read -p "please key months > " months
	   echo $months 
	   bc <<- EOF
	   		scale=10	
	   		i = (($interset / 12))
			p = $principal
			n = $months
			a = p * ((i * (( i+1 )^n)) / (((1+i) ^ n)-1 ))
			print a ,"\n"
		EOF
		;;
	2) usage
		;;
	esac
done

